FROM debian:buster
RUN apt-get update \
        && apt-get -y install apt-utils mariadb-server mariadb-client \
        && rm -rf /var/lib/mysql \
        && mkdir -p /var/lib/mysql /run/mysqld \
        && chown -R mysql:mysql /var/lib/mysql  /run/mysqld \
        && chmod 777 /var/run/mysqld\
		&&  apt-get -y install emacs

VOLUME /var/lib/mysql

COPY ./tools/entrypoint.sh ./
#COPY ./dump.sql ./


RUN mysql_install_db --user=mysql --datadir=/var/lib/mysql


EXPOSE 3306

ENTRYPOINT ["./entrypoint.sh"]
